### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by foreright360** [mopidy/mopidy-gmusic#102]
Do I need a certain version of python or pip to install?  Here's my output after running sudo pip install mopidy-gmusic:

``` python
Collecting mutagen>=1.18 (from gmusicapi>=6.0->mopidy-gmusic)
  Using cached mutagen-1.31.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-bb1a7m/mutagen/setup.py", line 222, in <module>
        from mutagen import version_string
      File "mutagen/__init__.py", line 23, in <module>
        from mutagen._util import MutagenError
      File "mutagen/_util.py", line 452
        if c == u"\x00":
                      ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bb1a7m/mutagen
```

**Comment by iosnewbie** [comment]
Hey, I'm just getting a similar error when installing on a Raspberry Pi 2 with Raspbian jessie:

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-LLa7cn/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-gfrHQH-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-LLa7cn/pycrypto
Storing debug log for failure in /root/.pip/pip.log

**Comment by jodal** [comment]
@foreright360 This looks like an issue with installing mutagen, not Mopidy-Spotify, so you should ask for help at https://discuss.mopidy.com/ since this isn't a bug in Mopidy-GMusic. Please include the exact `pip` command you ran to get this output and the output of `pip --version`, as that will include what Python version you're installing into.

@iosnewbie That doesn't look very similar at all. The first is a syntax error in Python. The second is a C compiler failing. Also the issue is with installing pycrypto, not Mopidy-GMusic, so you should ask for help at https://dicuss.mopidy.com/ since this isn't a bug in Mopidy-GMusic. Please include the full log when asking for help there.
