### ISSUE TITLE
Don't list artists that are only on compilations

### ISSUE THREAD

**Issue by jjok** [mopidy/mopidy-gmusic#129]
When I go to My Library on the Google Play Music website, it doesn't list compilation artists, and it would be nice if we could do the same here.

Maybe there could be a "list compilation artists" option in the config, so people can choose?

**Comment by belak** [comment]
I've actually been looking at completely reworking the library... I haven't decided how to best strike a balance between matching the web UI and making it convenient for mpd clients quite yet, but I'll definitely keep this in mind when I do that.

**Comment by jjok** [comment]
Great, thanks.

**Comment by jjok** [comment]
What are your other plans for this library? Maybe you could add a TODO list in the README, or open them as issues?

**Comment by belak** [comment]
Sure, I've put a list of how I'd like for the library to act in #132

**Comment by belak** [comment]
This will be resolved when #131 goes in. One of the main pain points was related to how to handle Album Artists (because gmusic doesn't actually give us an artist ID).

#131 also doesn't *exactly* check if the album is a compilation, it just checks if the album artist doesn't appear in any of the tracks.
