### ISSUE TITLE
Real playlist support

### ISSUE THREAD

**Issue by belak** [mopidy/mopidy-gmusic#136]
Right now, there's no saving/deleting/changing playlists. It would be nice if that were possible.

Additionally, it would be nice if there was a dynamic playlist for the library, so you could add tracks to your library (and maybe even rate them) without leaving mopidy. #104 also requested thumbsup/thumbsdown playlists.
- [ ] Playlist creating
- [ ] Playlist deleting
- [ ] Playlist changing
- [ ] Dynamic playlists (thumbs up, etc)

**Comment by j10sanders** [comment]
Why are playlists loaded into a parent directory of Google Music?  It's inconsistent with the rest of the Google Music experience inside mopidy.  

If there isn't a really good reason, I can start working on unifying the experience!

**Comment by belak** [comment]
I'm not really sure. It was like that when I picked this up. Improvements would be welcomed!

**Comment by j10sanders** [comment]
In the meantime for #104, I can go ahead and change the names of "promoted" to "Thumbs Up".  I don't think "promoted" playlists exist anymore.  Would that pull request get accepted?

**Comment by j10sanders** [comment]
I think the playlist format was copied from mopidy-spotify, but that it doesn't make sense here.  So I think I should make playlists essentially the same as "radio" in library.py (although that is already a large file).

I'm really trying to get my head around this code base.  If someone can give more info into why playlist support is coded so differently from artists, tracks, albums, and radio... (@jodal ?) that would be appreciated.

**Comment by belak** [comment]
I'm pretty much always in IRC (#mopidy on freenode) so if you want to chat more, feel free to ping me there.

Really, any dynamic playlist support would probably be accepted, unless there's a compelling reason to avoid it. I'm just trying to clean up some of the issues before releasing v2.0.

**Comment by adnidor** [comment]
I just looked into this a bit.

My observations:

- mopidy does not support changing a playlist incremental (i.e. moving tracks around, adding tracks) but only a complete replacement of the previous playlist
- gmusic only supports incremental changes

One possibility to work around this is to delete the entire playlist contents every time mopidy changes something and add all tracks again.
I don't like this approach because it feels like a bull in a china shop, (probably) destroys metadata, and there's a high chance of breaking something (for example an error between deleting playlist and adding tracks back would result in a lost playlist)

Another approach is to compare the existing playlist with the new playlist, work out what changed and translate that into gmusic operations.
This is the better approach, but rather difficult to implement.

Creating, deleting playlists is no problem, probably done in one API call.

For the special Promoted/Thumbs up playlist there are other issues. We can't control ordering because it is not a "real" playlist but a collection of songs with a specific attribute. Removing/adding songs can be done by adding/removing the Thumbs Up rating from the song, but operations going further than that can't be done.
Of course there's the possibility of taking the approach of removing all songs and adding them back in the order we want, but there is no guarantee that Google preserves our ordering, and this is even uglier than taking that approach to regular playlists.

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.
