### ISSUE TITLE
"bad handshake"

### ISSUE THREAD

**Issue by jjok** [mopidy/mopidy-gmusic#137]
Was there an official fix/workaround for #103?

I've been reinstalling an older version of `certifi` every time I upgrade an extension.

```
sudo pip uninstall -y certifi
sudo pip install certifi==2015.04.28
```

It would be good to add whatever fix you recommend to the README, as per https://github.com/mopidy/mopidy-gmusic/issues/103#issuecomment-164487465 if it's a problem a lot of people have.

**Comment by belak** [comment]
It looks like the recommended method is to upgrade to openssl >= 1.0.2. However if this isn't possible, the downgrade should work.

I didn't run into this because I'm running an upgraded version of openssl.

https://github.com/certifi/python-certifi/issues/26 mentions several workarounds. I'll list them in order of preference:

* Install OpenSSL >= 1.0.2
* Run `python -c 'import certifi; print certifi.old_where()'`, then assign the result of that to the `REQUESTS_CA_BUNDLE` environment variable.
* Downgrade to `certifi==2015.04.28`

I will update the README with this information later today.

**Comment by belak** [comment]
The readme update has been pushed to the develop branch.

**Comment by jjok** [comment]
Thanks.

I actually updated to the latest develop version of mopidy-gmusic last night, after running an `apt-get upgrade` and I haven't seen the issue for the first time. Maybe the upgrade gave me the OpenSSL >= 1.0.2?
