### ISSUE TITLE
I cant search song or artist

### ISSUE THREAD

**Issue by eagj** [mopidy/mopidy-gmusic#179]
When i make a search (for example daft punk) i see an artist, but when i enter are empty, the same if i search for song or anything. I only can use mopidy to hear radio artists, is normal?
Thanks you.

**Comment by jjok** [comment]
Do you have an All Access account? Have you uploaded any of your own tracks to Google Play Music?

**Comment by mkriegl** [comment]
I got a similar issue. No Album, Track or Artist is listed. Only one empty folder in Radio called "I'm feeling lucky". I am not sure wether "all access" is in Germany the single user with unlimited access with 77 songs uploaded. 
It would be great to get some help, because it already took me a long time to get even gmusic on mopidy running :-)

**Comment by eagj** [comment]
My solution was a chromecast audio... Is sad but to me was the best
