### ISSUE TITLE
Gapless Playback

### ISSUE THREAD

**Issue by hechtus** [mopidy/mopidy-gmusic#2]
Looking up the URL stream takes too long for gapless playback. I also tried to to act on the playbin about-to-finish callback which comes a bit earlier than the MESSAGE_EOS message. This seems to work, but the URL lookup is still too slow.

**Comment by belak** [comment]
I believe this is fixed. I have a few tracks that have pops when playing, but I think that's an issue with the tracks in gmusic, rather than an issue with the implementation. If people are still having problems with this, let me know, and please provide example tracks so I can test with the same input.

Thanks!
