### ISSUE TITLE
Too old httplib2

### ISSUE THREAD

**Issue by ErLitri** [mopidy/mopidy-gmusic#91]
I just can't work it out. This is what I get:

```
INFO     Disabled extension gmusic: (httplib2 0.9 (/usr/lib/python2.7/dist-packages), Requirement.parse('httplib2>=0.9.1'), set(['oauth2client']))
```

Httplib2 and oauth2client installed....don't know what I could do now, any suggestions?

**Comment by Moult** [comment]
It can't find your httplib2, even if you say you have it installed. Try `mopidy deps`.

**Comment by jodal** [comment]
The error here says that you have httplib2 0.9, but the version of oauth2client installed requires httplib2 >= 0.9.1.

Since your httplib2 is located in `/usr/lib/python2.7/dist-packages`, I'm quite certain that you have httplib2 from a Debian package and that you're running jessie (ref. https://packages.debian.org/search?keywords=python-httplib2).

Possible solutions includes:

- install a newer httplib2 (either using pip or the 2.9.1 package from Debian testing)
- install an older oauth2client which doesn't require anything more than httplib2

I'm fairly certain this has been discussed somewhere before, but I failed to find a similar topic at https://discuss.mopidy.com.

Anyway, https://discuss.mopidy.com is the proper place to continue the discussion if you're still having problems with this.
