### ISSUE TITLE
With gmusicapi 7.0.0.dev0, I can't get stations to appear in the playlist or more than 3 stations to appear in Browse

### ISSUE THREAD

**Issue by maemigh** [mopidy/mopidy-gmusic#93]
I've tried these options, but they don't seem to do anything:

```
show_radio_stations_browse = true
show_radio_stations_playlist = true
max_radio_stations = 0
max_radio_tracks = 25
```

**Comment by jodal** [comment]
Is this still an issue with 7.0.0 or 7.0.1?

**Comment by jodal** [comment]
I can reproduce this. It seems to be caused by simon-weber/gmusicapi#365. I'm not sure if the "I'm feeling lucky" station no longer exists and we should simply ignore it, or if this is just an issue with my fresh Google Play Music account. Feel free to follow my steps in the linked issue and test if you experience the same with your account.
